---
version: '3'

services:
  mongodb:
    restart: always
    build: .
    image: yolk/mongo
    volumes:
      - ./docker_volumes/mongo-data:/data/db
    ports:
      - "27017:27017"
    command: mongod
